# NumPy - Numerical Python

In [1]:
import numpy as np

List vs Numpy - Time Taken

In [2]:
from time import process_time#process_time measure time for a aparticular process

Time taken by a list

In [3]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]#adding 5 to each value i the python_list

end_time = process_time()

print(end_time - start_time)
#so basically in this cell we made a list and added 10000 values in it then added 5 to each value in the list n calc time taken to add 5 in each value of the list

0.0


In [4]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5  #np_array= np_array + 5

end_time = process_time()

print(end_time - start_time)

0.0


In [5]:
print(np_array)

[    5     6     7 ... 10002 10003 10004]


Numpy Arrays

In [6]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [7]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
a.shape

(4,)

In [10]:
b = np.array([(1,2,3,4),(5,6,7,8)])#2-D numpy array
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
b.shape

(2, 4)

In [12]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays # so initial placeholders initiates an array with a particular value

In [15]:
# create a numpy array of Zeros
x = np.zeros((4,5))#np.zeros method initiate all zeroes in an array and 4,5 is the rows, columns
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
# array of a particular value, in this case 8
z = np.full((5,4),8)
print(z)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [20]:
# create an identity matrix(all diag value is 1 others are 0 and have same rows and columns)
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [21]:
# create a numpy array with random values
b = np.random.random((3,4)) #it will give any random value # all the value generated will be bw 0 and 1 in this case
print(b)

[[0.46905277 0.28451766 0.4088573  0.92743203]
 [0.84426264 0.21601715 0.87289428 0.07759539]
 [0.30374819 0.6859188  0.61259878 0.2530663 ]]


In [22]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))#random values bw 10 and 100 will be given 
print(c)

[[90 74 25 44 58]
 [86 81 89 30 29]
 [80 32 39 43 75]]


In [23]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)#starting with 10 ending with 30 with equal gap of 5
print(d)

[10. 15. 20. 25. 30.]


In [24]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [25]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [26]:
c = np.random.randint(10,90,(5,5))
print(c)

[[88 86 89 77 16]
 [46 13 11 20 17]
 [87 78 10 43 82]
 [36 61 45 21 52]
 [17 61 24 23 64]]


In [27]:
# array dimension
print(c.shape)

(5, 5)


In [28]:
# number of dimensions
print(c.ndim)

2


In [29]:
# number of elements in an array
print(c.size)

25


In [30]:
# checking the data type of the values in the array
print(c.dtype)

int32


Mathematical operations on a np array

In [31]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [32]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [33]:
print(a)
print(b)

[[5 4 8]
 [0 9 9]
 [2 7 3]]
[[18 10 16]
 [13 14 19]
 [14 11 19]]


In [34]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[23 14 24]
 [13 23 28]
 [16 18 22]]
[[-13  -6  -8]
 [-13  -5 -10]
 [-12  -4 -16]]
[[ 90  40 128]
 [  0 126 171]
 [ 28  77  57]]
[[0.27777778 0.4        0.5       ]
 [0.         0.64285714 0.47368421]
 [0.14285714 0.63636364 0.15789474]]


In [35]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [36]:
print(a)
print(b)

[[1 1 7]
 [4 8 6]
 [9 6 0]]
[[14 12 11]
 [11 17 15]
 [15 11 17]]


In [37]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[15 13 18]
 [15 25 21]
 [24 17 17]]
[[-13 -11  -4]
 [ -7  -9  -9]
 [ -6  -5 -17]]
[[ 14  12  77]
 [ 44 136  90]
 [135  66   0]]
[[0.07142857 0.08333333 0.63636364]
 [0.36363636 0.47058824 0.4       ]
 [0.6        0.54545455 0.        ]]


Array Manipulation

In [38]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[8 1 5]
 [4 4 3]]
(2, 3)


In [39]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[8 4]
 [1 4]
 [5 3]]
(3, 2)


In [40]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 1 4]
 [5 7 2]]
(2, 3)


In [41]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[5 5]
 [1 7]
 [4 2]]
(3, 2)


In [42]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[6 1 5]
 [8 2 6]]
(2, 3)


In [43]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[6 1]
 [5 8]
 [2 6]]
(3, 2)
